server:
    port: 8081
spring:
  application:
    name: vault
  datasource:
    url: jdbc:h2:mem:vaultdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/vault-realm
          jwt-set-uri: http://localhost:8080/realms/vault-realm/protocol/openid-connect/certs

