apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:latest
          ports:
            - containerPort: 8081
          env:
            - name: ENCRYPTION_SECRET
              value: "AbCdEfGhIjKlMnOpQrStUvWxYz123456"
            - name: ENCRYPTION_IV
              value: "AbCdEfGhIjKlMnOp"


