name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          projectKey: avinash-dev_vault
          organization: avinash-dev
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Dummy: Add your SonarQube token in repo secrets
          SONAR_HOST_URL: 'https://sonarcloud.io' # Dummy: Replace with your SonarQube server URL


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Dummy: Add your DockerHub username in repo secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Dummy: Add your DockerHub token in repo secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: avial1998/vault:latest # Dummy: Replace with your Docker repo/image

  deploy:
    needs: build
    runs-on: self-hosted # Dummy: Replace with your deployment environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest Docker image
        run: docker pull avial1998/vault:latest # Dummy: Replace with your Docker repo/image

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/vault-deployment.yaml
          kubectl apply -f deployment/vault-service.yaml

